---
#
# Ansible managed
#
repository:
  description: Install and configure logstash on your system.
  homepage: https://robertdebock.nl/
  topics: logstash, ansible, molecule, tox, playbook, hacktoberfest
