---
#
# Ansible managed
#
repository:
  description: Install and configure Logstash on your system.
  homepage: https://robertdebock.nl/
  topics: logstash, monitoring, ansible, molecule, tox, playbook
