---
# tasks file for logstash

- name: include assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: install logstash
  package:
    name: "{{ logstash_package }}"
    state: present

- name: start logstash
  service:
    name: logstash
    state: started
