---
# tasks file for logstash

- name: Include assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: Install logstash
  ansible.builtin.package:
    name: "{{ logstash_package }}"
    state: present

- name: Start logstash
  ansible.builtin.service:
    name: logstash
    state: started
    enabled: yes
