---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: check if connection still works
      ansible.builtin.ping:

    - name: check logstash version
      command:
        cmd: /usr/share/logstash/bin/logstash --version
      register: logstash_test_one
      failed_when:
        - '"7" not in logstash_test_one.stdout'
