---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: check logstash version
      ansible.builtin.command:
        cmd: /usr/share/logstash/bin/logstash --version
      register: logstash_test_one
      failed_when:
        - '"7" not in logstash_test_one.stdout'
